# netlify.toml
[build]
  command = "pnpm install && pnpm run build"
  publish = ".netlify/public"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs" # ou noutro plugin se precisares
